### PR TITLE
zkSwap Finance fixed bugs

### PR DESCRIPTION
**Pull request by ZkSwapFinance**

### CODE REVIEW

**Comment by llamatester** [comment]
The emissions chart produced by "protocols/zkswap_finance.ts" should be below: 
 
 emissions schedule

**Comment by ZkSwapFinance** [comment]
@llamatester @plays-jobim 

I'm truly sorry for bothering you so many times. Due to a typo problem, our tokenomics and emission chart are incorrect.

We hope you can merge the updates for us soon, as this issue is quite important for our project.

Thank you very much. 

We're looking forward to seeing the new update.

**Comment by ZkSwapFinance** [comment]
@waynebruce0x

I'm truly sorry for bothering you so many times. Due to a typo problem, our tokenomics and emission chart are incorrect.

We hope you can merge the updates for us soon, as this issue is quite important for our project.

Thank you very much.

We're looking forward to seeing the new update.

**Comment by ZkSwapFinance** [comment]
@waynebruce0x @realdealshaman, Could you please review and integrate the latest update into the Unlock information?

**Comment by Define101** [comment]
Hello guys
Is the image correct?

**Comment by ZkSwapFinance** [comment]
> Hello guys Is the image correct?

Yes, bro. The image is correct. Looking forward to merging the version.

**Comment by ZkSwapFinance** [comment]
> Hello guys Is the image correct?

Could you please assist us? We have been waiting for two weeks.

**Comment by ZkSwapFinance** [comment]
Dear Definae101,

The image is correct. Could you please assist us in updating it?

Many thanks,
Ryan

**Comment by Define101** [comment]
Done

**Comment by ZkSwapFinance** [comment]
> Done

Thank you so much. We're looking forward to the Unlock page update.

**Comment by ZkSwapFinance** [comment]
Thank you, bro. Hope you have a nice day!

**Pull request merged**
