### PR TITLE
Equilibre

### PR DESCRIPTION
**Pull request by waynebruce0x**

### CODE REVIEW

**Comment by llamatester** [comment]
The emissions chart produced by "protocols/equilibre.ts" should be below: 
 
 emissions schedule

**Comment by pythinking** [comment]
@llamatester This looks fine?

The equilibre chart produced starts on 22/02/23 and ends on 22/02/25 (dates in format DD/MM/YY)
community emissions total 34402334
team emissions total 18000000
grants emissions total 16000000
airdrop emissions total 500000
liquidity emissions total 100000
for an overall of 69002334.18565154 tokens emitted


result

**Comment by pythinking** [comment]
@llamatester Thank you. I've made the changes. Please let me know if looks fine.

result

**Comment by pythinking** [comment]
@llamatester Thank you very much. It worked like a charm!

**Pull request merged**
